### ISSUE TITLE
미션 화면 구현

### ISSUE THREAD

**Issue by Tnalxmsk** [9oormthon-univ/2024_DANPOONG_TEAM_8_FE#10]
## ✅ Description
미션 화면 컴포넌트 구현 및 기록 작성, 완료 Flow 구현
## ✔️ TODO
- [x] 미션 화면 Tabs 구현
- [x] 자립 목표 Tab 현재 목표 및 자립 목표 리스트
- [x] 진행중인 미션, 완료한 미션 Tab 및 공통 컴포넌트 구현
- [x] 기록 작성 페이지 및 완료
- [x] 완료 미션 상세 페이지
