### ISSUE TITLE
미션 목표 설정 화면 구현

### ISSUE THREAD

**Issue by Tnalxmsk** [9oormthon-univ/2024_DANPOONG_TEAM_8_FE#15]
## ✅ Description
자립 목표 영역 선택 및 사전 점검표 화면
## ✔️ TODO
- [x] 자립 목표 영역 선택
- [x] 자립 목표 영역 선택 확인
- [x] 선택 목표 사전 점검표
