### ISSUE TITLE
미션 관련 API 및 UI 작업

### ISSUE THREAD

**Issue by Tnalxmsk** [9oormthon-univ/2024_DANPOONG_TEAM_8_FE#38]
## ✅ Description
미션 관련 수정 작업

## ✔️ TODO
- [x] 미션 목록 화면 디자인 수정
- [x] 미션 기록 작성 화면 API Res 타입 수정
- [x] Post 기록 작성 api 점검
- [x] 기록 작성 화면 UI 디자인 수정
