### ISSUE TITLE
지원 제도 및 목표 선택 시 멘트 수정

### ISSUE THREAD

**Issue by Tnalxmsk** [9oormthon-univ/2024_DANPOONG_TEAM_8_FE#68]
## ✅ Description
더미 데이터 추가 및 text 수정

## ✔️ TODO
- [x] 지원제도 mock 데이터
- [x] 목표 선택 후 해당 영역 멘트 추가
- [x] 기록 작성시 글자수 color 변경 추가
